### ISSUE TITLE
7.3.2 breaks updateTriggers for TileLayer

### ISSUE THREAD

**Issue by aepton** [uber/deck.gl#3776]
#### Description
As of 7.3.2, updates no longer fire to `TileLayer` when values passed to `updateTriggers` arrays change. This behavior isn't present in 7.3.1, which works as expected. As a result, the layer never seems to update.

#### Repro Steps
Instantiate a `TileLayer`, add `updateTriggers` as below, and watch the layer fail to update even as the map zoom level changes - but only on 7.3.2:

```
const tileLayer = new TileLayer({
    getLineWidth: this.getLineWidth,
    updateTriggers: {
        getLineWidth: [parseInt(viewState.zoom)]
    },
    id: 'sample-tiles',
    getTileData: ({ x, y, z }) => {
      const url = this.getURL(x, y, z);
      return axios
        .get(url, {
          responseType: 'arraybuffer'
        })
        .then(response => {
          return this.parseTile(response.data);
        })
        .catch(error => {
          console.log(`Received error ${error} fetching ${url}`);
          return [];
        });
    }
  });
```

#### Environment (please complete the following information):
 - Framework Version: deck.gl 7.3.2
 - Browser Version: all
 - OS: all

#### Logs
None

**Comment by ibgreen** [comment]
@aepton Thanks for reporting, this is an interesting and unforeseen consequence of a `TileLayer` optimization we did in 7.3.2.

Basically, there was a perf issue reported on the TileLayer #3695, and we did a quick fix for it by caching the sublayer rendering.

But this does have the effect of not propagating update triggers down to the sublayers on every update.

We need some ideas. How about:

- Until we have time to do a more solid performance overhaul, one option might be to add an additional prop (`_cacheLayers`) that determines if sublayers are generated each render or not.

**Comment by Pessimistress** [comment]
We should be able to check `changeFlags.updateTriggersChanged` in updateState` and invalidate the cache from there.

**Comment by ibgreen** [comment]
@xintongxia This issue presumably affects both `TileLayer` and `Tile3DLayer`.

**Comment by 1chandu** [comment]
@xintongxia , this is fixed in 7.3.3 right, can we close this? if not move it to 7.3.4 milestone

**Comment by xintongxia** [comment]
yes, close it.

**Comment by aepton** [comment]
This seems to still be broken, unfortunately, even on `8.0.14` - I'm still seeing the same behavior.
