### ISSUE TITLE
picking feature issue: glScissor: width < 0

### ISSUE THREAD

**Issue by rivulet-zhang** [uber/deck.gl#776]
This occasionally occurs during the program initialization stage. The last line (192 messages) was triggered by mouse-moving on the map. 
<img width="500" alt="screen shot 2017-07-11 at 4 08 35 pm" src="https://user-images.githubusercontent.com/10911507/28088918-4335fd26-6655-11e7-9d43-e81b56667524.png">
I was working on the `tagmap` example, but it occurred even though I disabled my code. Seems to be relevant to the picking feature in deck.gl.

**Comment by Pessimistress** [comment]
@rivulet-zhang This should have been fixed by https://github.com/uber/deck.gl/pull/756
Try install the latest beta.

**Comment by rivulet-zhang** [comment]
Hi @Pessimistress both beta.2 and beta.4 still have this issue. Here is the line of code that generates the negative `width` value in `draw-and-pick.js`:
`const width = Math.min(pickingFBO.width, deviceX + deviceRadius) - x + 1;`

When it occurs, I saw that the picking frame buffer (`pickingFBO`) had the size of 1000 (the default setting?) while the mouse position (`deviceX`) was outside the box. It looks like the frame buffer was not resized correctly.

**Comment by Pessimistress** [comment]
1000 is the default canvas size. Sounds like the canvas and picking framebuffer sizes are out of sync.
Can you try change `componentDidMount` to `componentWillMount` in app.js and see if the problem goes away?

**Comment by rivulet-zhang** [comment]
That fixed the issue. Thanks!
